apiVersion: v1
kind: ConfigMap
metadata:
  name: django-configmap
data:
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "goran"
  POSTGRES_PASSWORD: "goran"
  POSTGRES_DB: "cars2"