version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: cars2  # Name of the database for your app
      POSTGRES_USER: goran  # Your database username
      POSTGRES_PASSWORD: goran  # Your database password
    ports:
      - "5432:5432"  # Expose the PostgreSQL port
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist data between container restarts

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000  # Run Django's development server
    volumes:
      - .:/code  # Mount your local project directory inside the container
    ports:
      - "8000:8000"  # Expose the web service on port 8000
    depends_on:
      - db  # Ensure the database starts before the web service
    environment:
      DATABASE_URL: postgres://goran:goran@db:5432/cars2  # Connection string for Django to connect to PostgreSQL

volumes:
  db_data:  # Volume for persisting PostgreSQL data