version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: cars2
      POSTGRES_USER: goran
      POSTGRES_PASSWORD: goran
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://goran:goran@db:5432/cars2

volumes:
  db_data: